Develop
hatchi02/hotel_reservation4 pull request #1
Opened 2023-04-15 06:32 UTC by hatchi02

2023-04-15 09:29 UTC, TakuyaChida requested changes
課題のご提出ありがとうございます。
内容を確認いたしました。

予約時にエラーとなってしまっているため修正をお願いいたします。
予約開始日＞予約終了日とすることで下記のエラーとなってしまっています。
![スクリーンショット 2023-04-15 18 27 03](https://user-images.githubusercontent.com/74874584/232205489-725da980-c265-4333-b596-cbe3fe00ea73.png)

お手数ですがご確認をお願いいたします。

2023-04-15 09:29 UTC, TakuyaChida commented on app/views/rooms/own.html.erb
> +          <td><%= room.name %></td>s
不要なアルファベットが入力されてしまっています。
バグの原因となるので気をつけましょう。

2023-04-15 10:27 UTC, hatchi02 reviewed
fix an error when input a wrong checkin/checkout

2023-04-16 10:12 UTC, TakuyaChida requested changes
課題のご提出ありがとうございます！
内容を確認しました。

気になった点や、要件と相違がある箇所を洗い出しました。
全体的にエラーなく動作ができており素晴らしいと思いました。
また、PR作成時は完成品をレビューしてもらうことが大前提ですので、
エラーがある内容でPRを作成するのは御法度です。
実際の現場では信用問題に関わってくるため、**必ず**自身が実装した箇所全体のセルフチェック、セルフテストを行ってからPRを提出するようにしましょう！

該当箇所にPRコメントを記載いたしましたので、お手数ですが修正をお願いいたします。
他は大丈夫そうでした。

2023-04-16 10:12 UTC, TakuyaChida commented on app/views/rooms/index.html.erb
> +<h4><%= "#{Room.count}件が見つかりました。" %></h4>
[must]
こちら、検索で0件であった場合でも「○○件が見つかりました」とでてしまっています。
バグですのでこちら修正をお願いいたします。
![スクリーンショット 2023-04-16 18 47 30](https://user-images.githubusercontent.com/74874584/232291057-ad3cb2ac-51da-4288-9a39-3bdddc5def81.png)

2023-04-16 10:12 UTC, TakuyaChida commented on app/controllers/rooms_controller.rb
> +      @rooms = Room.where("address LIKE? AND name LIKE?", "%#{params[:search_area]}%","%#{params[:search_keyword]}%")
[must]
あいまい検索の要件を確認しましょう。

```
【エリア検索機能について】
 エリアは、東京・大阪・京都・札幌の4つとしてください。
 住所を対象とし、「あいまい検索」としてください。
【フリーワード検索機能について】
 施設名・施設詳細を対象とし、「あいまい検索」としてください。
```

フリーワードで検索してもエリア検索機能となってしまっています。
また、施設詳細が条件に含まれておらずHITしません。

2023-04-16 10:12 UTC, TakuyaChida commented on app/views/rooms/index.html.erb
> +  <% @rooms.each do |room| %>
[imo]
こちら必須ではありませんが、サイトの見た目を考えた場合にとても見ずらいので
一覧形式に直すほうが良いと思います。
ユーザビリティを考慮した実装を行うのもエンジニアとしてのスキル1つです。
![スクリーンショット 2023-04-16 18 53 30](https://user-images.githubusercontent.com/74874584/232291437-61225613-ad60-4299-b7ba-57c44aa826da.png)

2023-04-16 10:12 UTC, TakuyaChida commented on app/views/rooms/edit.html.erb
> +<h2>施設情報の編集</h2>
[must]
エラーで登録できなかった原因に関するバリデーションメッセージを該当箇所に表示するようにしましょう。
こちらではどこが原因で登録ができないのかわからない状態です。

![スクリーンショット 2023-04-16 19 03 25](https://user-images.githubusercontent.com/74874584/232292194-4d4d0114-22d5-4e0e-a430-3b095cb03215.png)

2023-04-16 10:12 UTC, TakuyaChida commented on app/views/rooms/new.html.erb
> +<% if flash[:warning] %>
[must]
エラーで登録できなかった原因に関するバリデーションメッセージを該当箇所に表示するようにしましょう。
こちらではどこが原因で登録ができないのかわからない状態です。
![スクリーンショット 2023-04-16 19 00 06](https://user-images.githubusercontent.com/74874584/232291775-8b094cf8-100c-46b8-8972-53cd2e769c2b.png)

2023-04-16 10:12 UTC, TakuyaChida commented on app/views/reservations/confirm.html.erb
> +<%= form_for @reservation, method: :post, url: reservations_path do |form| %>
[must]
エラーで登録できなかった原因に関するバリデーションメッセージを該当箇所に表示するようにしましょう。
こちらではどこが原因で登録ができないのかわからない状態です。

![スクリーンショット 2023-04-16 19 05 22](https://user-images.githubusercontent.com/74874584/232292971-6bf96b72-1b53-4e66-a862-7eaaa3c78f38.png)

2023-04-16 10:12 UTC, TakuyaChida commented on app/views/homes/index.html.erb
> +<h1>これはlocalhost3000 接続時に表示されるトップページ</h1>
[must]
不要な記述はPR作成前に削除するようにしてください。
または適切なタイトルに変更するようにしましょう。

2023-04-18 01:09 UTC, YamanakaSayaka commented
動作確認したところ、日付、人数を入力し予約しようとするとエラーとなりました。
![スクリーンショット 2023-04-18 10 06 29](https://user-images.githubusercontent.com/79829190/232643195-3d13f386-84af-4106-b835-b523c9dce04c.png)

動作確認の上、提出いただくようお願いします。

2023-04-20 01:41 UTC, MasahiroMatsuno reviewed
確認しました！LGTMです！
カリキュラムでの学びやカリキュラム外のプラスαの学びなども積極的に活かして実装できていたため素晴らしかったです。

以下アドバイスです。
(プルリク内のコメントも確認しておいてください！)
・コミットメッセージの残し方について
https://qiita.com/itosho/items/9565c6ad2ffc24c09364
・Pull Requestのdescriptionに実装した機能の概要や実装の際に迷った点やレビュアーに特に見てほしい点などを書くようにしましょう。
・テストについてもRspecを使っていきますので、
Everyday Rails等の書籍や、本書を訳された伊藤さんのqiitaの記事等を参考に学習を進めてみてください👍
https://leanpub.com/everydayrailsrspec-jp

以上、宿泊予約サービスアプリはLGTMです。
最終課題も頑張っていきましょう！
お疲れ様でした！

2023-04-20 01:41 UTC, MasahiroMatsuno commented on .gitignore
> +/public/uploads/*
対処できていますね👍
images配下の画像も差分に上がってしまっているので本来はこちらも差分に挙げないように対処したいです。

2023-04-20 01:41 UTC, MasahiroMatsuno commented on app/views/reservations/confirm.html.erb
> +<%= form_for @reservation, method: :post, url: back_reservation_path do |form| %>
インデントがずれているところが複数箇所あります。
また、改行の仕方にも統一感がないため読みにくくなっている箇所もあります。
基本的にインデントは半角スペース2つ分を一段、改行で間を開けるときは1行で十分ということを今後意識してみてください。

2023-04-20 01:41 UTC, MasahiroMatsuno commented on app/views/reservations/confirm.html.erb
> +<% end %>
行末は改行コードをいれるのが慣習になっています。このファイルだけではないのですが、挿入されていないので警告がでています。
（㊀マーク）エディタのプラグインによって自動挿入してくれる機能もありますので調べてみてください。
https://bottoms-programming.com/archives/indent-tab-space-and-new-line.html

2023-05-10 01:11 UTC, merged